/* Expressions idiomatiques reconnues dans les textes.
   Chaque ligne : [forme affichée, motif de recherche ('' = la forme affichée), sens en français, note facultative]
   Motif : ^verbe = toutes les formes du verbe (break, broke, broken…) ;
           (a|b) = au choix ; one's = my/your/his/her/its/our/their ou « X's » ;
           oneself = myself/yourself… ; sb, sth = un à trois mots quelconques ;
           mot? = mot facultatif. */
const IDIOMS = [
  ["There is such a thing as too much…", "there (is|was|'s) such a thing as too (much|many)", "On peut avoir trop de… ; l'excès nuit en tout.", "Formule très courante : « trop de … tue le … »."],
  ["There is no such thing as…", "there (is|was|'s) no such thing as", "… n'existe pas ; il n'y a pas de…", "Ex. : There's no such thing as a free lunch — rien n'est gratuit."],
  ["No such thing as a free lunch", "no such thing as a free lunch", "Rien n'est gratuit ; tout se paie."],
  ["Break the ice", "^break the ice", "Briser la glace."],
  ["Call it a day", "^call it a day", "S'arrêter là (pour aujourd'hui)."],
  ["Call it quits", "^call it quits", "En rester là, arrêter."],
  ["A piece of cake", "", "C'est du gâteau, c'est très facile."],
  ["Hit the nail on the head", "^hit the nail on the head", "Mettre le doigt dessus, viser juste."],
  ["Spill the beans", "^spill the beans", "Vendre la mèche."],
  ["Let the cat out of the bag", "^let the cat out of the bag", "Vendre la mèche."],
  ["Under the weather", "", "Patraque, pas en forme."],
  ["Once in a blue moon", "", "Tous les trente-six du mois, très rarement."],
  ["Cost an arm and a leg", "^cost an arm and a leg", "Coûter les yeux de la tête."],
  ["Bite the bullet", "^bite the bullet", "Serrer les dents et s'y résoudre."],
  ["Beat around the bush", "^beat (around|about) the bush", "Tourner autour du pot."],
  ["The last straw", "the (last|final) straw", "La goutte d'eau qui fait déborder le vase."],
  ["Miss the boat", "^miss the boat", "Rater le coche."],
  ["Pull someone's leg", "^pull one's leg", "Faire marcher quelqu'un, le taquiner."],
  ["See eye to eye", "^see eye to eye", "Être d'accord, voir les choses de la même façon."],
  ["Cut corners", "^cut corners", "Bâcler, rogner sur la qualité."],
  ["Get out of hand", "^get out of hand", "Échapper à tout contrôle, dégénérer."],
  ["Hang in there", "^hang in there", "Tiens bon !"],
  ["Not rocket science", "not rocket science", "Ce n'est pas sorcier."],
  ["Keep an eye on", "^keep an eye on", "Surveiller, garder un œil sur."],
  ["Go the extra mile", "^go the extra mile", "Faire un effort supplémentaire."],
  ["Make ends meet", "^make ends meet", "Joindre les deux bouts."],
  ["On the same page", "", "Sur la même longueur d'onde, d'accord sur l'essentiel."],
  ["Play it by ear", "^play it by ear", "Improviser, aviser au fur et à mesure."],
  ["Ring a bell", "^ring a bell", "Dire quelque chose (rappeler un souvenir)."],
  ["Take it easy", "^take it easy", "Se détendre ; y aller doucement."],
  ["Better late than never", "", "Mieux vaut tard que jamais."],
  ["The ball is in your court", "the ball (is|'s) in one's court", "La balle est dans ton camp : à toi d'agir."],
  ["Add insult to injury", "^add insult to injury", "Retourner le couteau dans la plaie ; pour ne rien arranger."],
  ["Get the hang of", "^get the hang of", "Prendre le coup de main pour."],
  ["Jump on the bandwagon", "^jump on the bandwagon", "Prendre le train en marche, suivre la mode."],
  ["Kill two birds with one stone", "^kill two birds with one stone", "Faire d'une pierre deux coups."],
  ["The elephant in the room", "", "Le sujet que tout le monde évite."],
  ["A blessing in disguise", "", "Un mal pour un bien."],
  ["Every cloud has a silver lining", "", "À quelque chose malheur est bon."],
  ["Speak of the devil", "(speak|speaking|talk|talking) of the devil", "Quand on parle du loup…"],
  ["Hit the sack", "^hit the (sack|hay)", "Aller se coucher."],
  ["Sit on the fence", "^sit on the fence", "Ne pas prendre parti."],
  ["Steal the show", "^steal the show", "Voler la vedette."],
  ["Take a rain check", "^take a rain check", "Remettre (une invitation) à plus tard."],
  ["Throw in the towel", "^throw in the towel", "Jeter l'éponge."],
  ["Cry over spilt milk", "^cry over (spilt|spilled) milk", "Se lamenter sur ce qui est fait et ne peut être changé."],
  ["Burn the midnight oil", "^burn the midnight oil", "Travailler tard dans la nuit."],
  ["Burn one's bridges", "^burn one's? bridges", "Couper les ponts, se fermer toute possibilité de retour."],
  ["Cross that bridge when we come to it", "^cross that bridge when sb ^come to it", "Chaque chose en son temps ; on verra le moment venu."],
  ["Face the music", "^face the music", "Assumer les conséquences."],
  ["Get cold feet", "^get cold feet", "Avoir la frousse, se dégonfler au dernier moment."],
  ["Back to the drawing board", "back to the drawing board", "Retour à la case départ (il faut tout repenser)."],
  ["Back to square one", "", "Retour à la case départ."],
  ["In the nick of time", "", "Juste à temps."],
  ["It takes two to tango", "^take two to tango", "Il faut être deux ; les torts sont partagés."],
  ["Leave no stone unturned", "^leave no stone unturned", "Remuer ciel et terre."],
  ["Let sleeping dogs lie", "", "Ne pas réveiller le chat qui dort."],
  ["No pain, no gain", "no pain no gain", "On n'a rien sans rien."],
  ["On thin ice", "", "Sur un terrain glissant."],
  ["Pull oneself together", "^pull oneself together", "Se ressaisir."],
  ["Rain cats and dogs", "^rain cats and dogs", "Pleuvoir des cordes."],
  ["Light at the end of the tunnel", "", "Le bout du tunnel."],
  ["So far, so good", "so far so good", "Jusqu'ici, tout va bien."],
  ["The best of both worlds", "", "Le meilleur des deux mondes."],
  ["With a grain of salt", "with a (grain|pinch) of salt", "Avec des pincettes, avec réserve."],
  ["Time flies", "time (flies|flew)", "Le temps passe vite."],
  ["Long story short", "", "Bref, pour faire court."],
  ["Twist someone's arm", "^twist one's arm", "Forcer la main à quelqu'un."],
  ["Under the radar", "", "Discrètement, sans attirer l'attention."],
  ["Wrap one's head around", "^wrap one's head around", "Arriver à comprendre (quelque chose de complexe)."],
  ["Judge a book by its cover", "^judge a book by its cover", "Juger sur les apparences.", "Don't judge a book by its cover : l'habit ne fait pas le moine."],
  ["A dime a dozen", "", "Monnaie courante, il y en a à la pelle."],
  ["Actions speak louder than words", "", "Les actes comptent plus que les paroles."],
  ["Bark up the wrong tree", "^bark up the wrong tree", "Faire fausse route, se tromper de cible."],
  ["In hot water", "", "Dans le pétrin."],
  ["Bend over backwards", "^bend over backwards", "Se mettre en quatre."],
  ["Between a rock and a hard place", "", "Entre le marteau et l'enclume."],
  ["By the skin of one's teeth", "by the skin of one's teeth", "De justesse."],
  ["Call the shots", "^call the shots", "Mener la barque, décider."],
  ["Come rain or shine", "", "Quoi qu'il arrive, qu'il pleuve ou qu'il vente."],
  ["Cut to the chase", "^cut to the chase", "Aller droit au but."],
  ["Down to earth", "down to earth", "Les pieds sur terre, simple."],
  ["Drop the ball", "^drop the ball", "Commettre une erreur, laisser tomber une responsabilité."],
  ["Easier said than done", "", "Plus facile à dire qu'à faire."],
  ["A fish out of water", "", "Comme un poisson hors de l'eau, pas à sa place."],
  ["A taste of one's own medicine", "a taste of one's own medicine", "La monnaie de sa pièce."],
  ["Get something off one's chest", "off one's chest", "Vider son sac, dire ce qu'on a sur le cœur."],
  ["The benefit of the doubt", "", "Le bénéfice du doute."],
  ["Go with the flow", "^go with the flow", "Se laisser porter, suivre le mouvement."],
  ["A lot on one's plate", "(a lot|lots|enough|too much) on one's plate", "Avoir du pain sur la planche."],
  ["Head over heels", "", "Éperdument (amoureux)."],
  ["Hit the road", "^hit the road", "Se mettre en route, partir."],
  ["Hold your horses", "^hold one's horses", "Du calme, pas si vite !"],
  ["In a nutshell", "", "En un mot, en résumé."],
  ["Keep one's fingers crossed", "fingers crossed", "Croiser les doigts."],
  ["Know the ropes", "^(know|learn|show) sb? the ropes", "Connaître (apprendre, montrer) les ficelles."],
  ["Let off steam", "^(let|blow) off steam", "Se défouler, décompresser."],
  ["Lose one's temper", "^lose one's temper", "Se mettre en colère, perdre son calme."],
  ["Make a mountain out of a molehill", "^make a mountain out of a molehill", "En faire tout un plat, une montagne."],
  ["Miss the point", "^miss the point", "Passer à côté de l'essentiel."],
  ["Not my cup of tea", "not one's cup of tea", "Ce n'est pas mon truc."],
  ["Off the top of my head", "off the top of one's head", "De mémoire, comme ça, sans vérifier."],
  ["On cloud nine", "", "Aux anges, au septième ciel."],
  ["Once and for all", "", "Une fois pour toutes."],
  ["Out of the blue", "", "Sans prévenir, tout à coup."],
  ["Over the moon", "", "Fou de joie, ravi."],
  ["Pass the buck", "^pass the buck", "Refiler la responsabilité à quelqu'un d'autre."],
  ["Put all one's eggs in one basket", "all one's eggs in one basket", "Mettre tous ses œufs dans le même panier."],
  ["Read between the lines", "^read between the lines", "Lire entre les lignes."],
  ["Run out of steam", "^run out of steam", "S'essouffler, être à bout."],
  ["Save face", "^save face", "Sauver la face."],
  ["Set in stone", "", "Gravé dans le marbre, définitif."],
  ["Sleep on it", "^sleep on it", "Laisser reposer la décision : la nuit porte conseil."],
  ["Take the bull by the horns", "^take the bull by the horns", "Prendre le taureau par les cornes."],
  ["Tie the knot", "^tie the knot", "Se marier."],
  ["The tip of the iceberg", "", "La partie émergée de l'iceberg."],
  ["The whole nine yards", "", "Le grand jeu, jusqu'au bout."],
  ["To be honest", "", "Pour être honnête, à vrai dire."],
  ["To tell the truth", "", "À vrai dire."],
  ["Turn a blind eye", "^turn a blind eye", "Fermer les yeux (sur quelque chose)."],
  ["Up in the air", "", "Incertain, en suspens."],
  ["Weather the storm", "^weather the storm", "Surmonter la tempête, tenir le coup."],
  ["When pigs fly", "when pigs (fly|can fly)", "Quand les poules auront des dents."],
  ["A penny for your thoughts", "", "À quoi penses-tu ?"],
  ["Cold turkey", "", "Arrêter net, d'un coup (une habitude, une drogue)."],
  ["Get the ball rolling", "^(get|set|start) the ball rolling", "Lancer les choses, amorcer."],
  ["Jump the gun", "^jump the gun", "Agir trop tôt, griller les étapes."],
  ["At arm's length", "at arm 's length", "À distance (garder quelqu'un à distance)."],
  ["By and large", "", "Dans l'ensemble."],
  ["All of a sudden", "", "Tout à coup."],
  ["As a matter of fact", "", "En fait, à vrai dire."],
  ["At the end of the day", "", "En fin de compte."],
  ["At the drop of a hat", "", "Sur-le-champ, sans hésiter."],
  ["Beat a dead horse", "^(beat|flog) a dead horse", "S'acharner pour rien, insister inutilement."],
  ["Bite off more than one can chew", "^bite off more than sb can chew", "Avoir les yeux plus gros que le ventre."],
  ["Break a leg", "^break a leg", "Bonne chance ! (au théâtre : « merde ! »)"],
  ["Come to terms with", "^come to terms with", "Accepter, se faire à."],
  ["Cut someone some slack", "^cut sb some slack", "Être indulgent avec quelqu'un."],
  ["Get one's act together", "^get one's act together", "Se reprendre en main, se secouer."],
  ["Give it a shot", "^give it a (shot|try|go|whirl)", "Essayer, tenter le coup."],
  ["It goes without saying", "^go without saying", "Ça va sans dire."],
  ["Have second thoughts", "^have second thoughts", "Avoir des doutes, hésiter à nouveau."],
  ["In the long run", "", "À long terme."],
  ["In the same boat", "", "Dans le même bateau, dans la même galère."],
  ["It's about time", "it (is|'s|was) about time", "Il était temps."],
  ["Keep in touch", "^(keep|stay|get) in touch", "Rester (se mettre) en contact."],
  ["Make up one's mind", "^make up one's mind", "Se décider."],
  ["No wonder", "", "Pas étonnant (que)."],
  ["Take for granted", "^take sb? for granted", "Tenir pour acquis."],
  ["The bottom line", "", "L'essentiel, le fin mot de l'histoire."],
  ["Think outside the box", "^think outside the box", "Sortir des sentiers battus."],
  ["Touch base", "^touch base", "Reprendre contact, faire un point rapide."],
  ["A far cry from", "", "Très loin de, rien à voir avec."],
  ["Make sense", "^make sense", "Avoir du sens, être logique."],
  ["On the other hand", "", "D'un autre côté, en revanche."],
  ["By the way", "", "Au fait, à propos."],
  ["Bear in mind", "^(bear|keep) in mind", "Garder à l'esprit."],
  ["Pull strings", "^pull (some|a few)? strings", "Faire jouer ses relations, pistonner."],
  ["Rock the boat", "^rock the boat", "Faire des vagues, semer le trouble."],
  ["Stab someone in the back", "^stab sb in the back", "Trahir, poignarder dans le dos."],
  ["Shoot oneself in the foot", "^shoot oneself in the foot", "Se tirer une balle dans le pied."],
  ["The devil is in the details", "the devil (is|'s) in the detail", "Le diable se cache dans les détails."],
  ["Down the rabbit hole", "", "Se perdre dans un sujet sans fin."],
  ["A chip on one's shoulder", "a chip on one's shoulder", "Être aigri, avoir une rancune tenace."],
  ["Devil's advocate", "devil 's advocate", "L'avocat du diable."],
  ["Pull one's weight", "^pull one's weight", "Faire sa part (du travail)."],
  ["A storm in a teacup", "a storm in a teacup", "Une tempête dans un verre d'eau."],
  ["Put one's foot in it", "^put one's foot in (it|one's mouth)", "Mettre les pieds dans le plat, faire une gaffe."],
  ["Get on someone's nerves", "^get on one's nerves", "Taper sur les nerfs."],
  ["Drive someone up the wall", "^drive sb up the wall", "Rendre quelqu'un fou (d'exaspération)."],
  ["Butterflies in one's stomach", "butterflies in one's stomach", "Avoir le trac, l'estomac noué."],
  ["See red", "^see red", "Voir rouge, se mettre en colère."],
  ["A bitter pill to swallow", "", "Une pilule difficile à avaler."],
  ["Hit the ground running", "^hit the ground running", "Démarrer sur les chapeaux de roue."],
  ["Too good to be true", "", "Trop beau pour être vrai."],
  ["Take a toll", "^take (a|its|their|his|her|an) (heavy)? toll", "Avoir des effets néfastes, laisser des traces."],
  ["Make no bones about", "^make no bones about", "Ne pas cacher, dire franchement."],
  ["Go to great lengths", "^go to (great|any|extraordinary) lengths", "Se donner beaucoup de mal, ne reculer devant rien."],
  ["More often than not", "", "Le plus souvent."],
  ["Stand one's ground", "^stand one's ground", "Tenir bon, ne pas céder."],
  ["Have the last laugh", "^have the last laugh", "Rira bien qui rira le dernier."],
  ["Get the picture", "^get the picture", "Piger, comprendre la situation."],
  ["It's a small world", "it (is|'s) a small world", "Le monde est petit."],
  ["Kick the bucket", "^kick the bucket", "Casser sa pipe (mourir)."],
  ["Bury the hatchet", "^bury the hatchet", "Enterrer la hache de guerre."],
  ["Go out on a limb", "^go out on a limb", "Prendre un risque, s'avancer."],
  ["Head in the clouds", "head in the clouds", "Avoir la tête dans les nuages."],
  ["Lend a hand", "^lend sb? a hand", "Donner un coup de main."],
  ["Put up with", "^put up with", "Supporter, tolérer."],
  ["Look forward to", "^look forward to", "Avoir hâte de, attendre avec impatience."],
  ["Fed up with", "fed up", "En avoir marre (de)."],
  ["Have a crush on", "^have a crush on", "Avoir le béguin pour."],
  ["On purpose", "", "Exprès, délibérément."],
  ["By heart", "", "Par cœur."],
  ["At stake", "", "En jeu."],
  ["For what it's worth", "for what (it's|it is) worth", "Pour ce que ça vaut."],
  ["The more the merrier", "", "Plus on est de fous, plus on rit."],
  ["Better safe than sorry", "", "Prudence est mère de sûreté."],
  ["Curiosity killed the cat", "", "La curiosité est un vilain défaut."],
  ["When in Rome", "", "À Rome, fais comme les Romains."],
  ["The early bird catches the worm", "the early bird", "L'avenir appartient à ceux qui se lèvent tôt."],
  ["Don't count your chickens", "^count one's chickens", "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué."],
  ["Practice makes perfect", "", "C'est en forgeant qu'on devient forgeron."],
  ["Out of sight, out of mind", "out of sight out of mind", "Loin des yeux, loin du cœur."],
  ["The grass is always greener", "the grass is always greener", "L'herbe est toujours plus verte ailleurs."],
  ["Under the same roof", "", "Sous le même toit."],
  ["A matter of time", "", "Une question de temps."],
  ["In the meantime", "", "En attendant, entre-temps."],
  ["Sooner or later", "", "Tôt ou tard."],
  ["Every now and then", "every (now and then|now and again|so often)", "De temps en temps."],
  ["As far as I know", "as far as (i|we) know", "Pour autant que je sache."],
  ["Last but not least", "", "Enfin et surtout ; le dernier mais pas le moindre."],
  ["Out of the question", "", "Hors de question."],
  ["Make the most of", "^make the most of", "Profiter au maximum de, tirer le meilleur parti de."],
  ["Get rid of", "^get rid of", "Se débarrasser de."],
  ["Take advantage of", "^take advantage of", "Profiter de ; abuser de."],
  ["Run out of", "^run out of", "Manquer de, être à court de."],
  ["Give up", "^give up", "Abandonner, renoncer."],
  ["Find out", "^find out", "Découvrir, apprendre."],
  ["Figure out", "^figure out", "Comprendre, trouver (la solution)."],
  ["Come up with", "^come up with", "Trouver, proposer (une idée)."],
  ["Carry on", "^carry on", "Continuer."],
  ["Add fuel to the fire", "^add fuel to … (fire|flames|flame)", "Jeter de l'huile sur le feu ; attiser, alimenter.", "Parfois détourné en positif : « alimenter » (une passion, une envie, une quête)."],
  ["Fan the flames", "^fan the (flames|flame)", "Attiser (un conflit, une passion)."],
  ["Pour oil on troubled waters", "^pour oil on troubled waters", "Calmer le jeu, apaiser les esprits."],
  ["Play with fire", "^play with fire", "Jouer avec le feu."],
  ["Where there's smoke, there's fire", "where there (is|'s) smoke", "Il n'y a pas de fumée sans feu."],
  ["Out of the frying pan into the fire", "out of the frying pan", "Tomber de Charybde en Scylla, aller de mal en pis."],
  ["Get on like a house on fire", "like a house on fire", "S'entendre à merveille."],
  ["Under fire", "", "Sous le feu des critiques."],
  ["Take something to heart", "^take sb to heart", "Prendre à cœur, être très affecté par."],
  ["Have a change of heart", "^have a change of heart", "Changer d'avis."],
  ["Break someone's heart", "^break one's heart", "Briser le cœur de quelqu'un."],
  ["A heart of gold", "", "Un cœur d'or."],
  ["At heart", "", "Au fond (de soi)."],
  ["Wear one's heart on one's sleeve", "^wear one's heart on one's sleeve", "Montrer ouvertement ses sentiments."],
  ["In the blink of an eye", "", "En un clin d'œil."],
  ["The big picture", "", "La vue d'ensemble."],
  ["Keep a low profile", "^keep a low profile", "Se faire discret."],
  ["The wrong end of the stick", "", "Comprendre de travers."],
  ["Go downhill", "^go downhill", "Se dégrader, aller de mal en pis."],
  ["Down the drain", "", "Gaspillé, parti en fumée."],
  ["Over the top", "", "Exagéré, excessif."],
  ["On the edge of one's seat", "on the edge of one's seat", "Tenu en haleine."],
  ["On the tip of one's tongue", "on the tip of one's tongue", "Sur le bout de la langue."],
  ["Bite one's tongue", "^bite one's tongue", "Se retenir de parler, tenir sa langue."],
  ["Hold one's tongue", "^hold one's tongue", "Tenir sa langue, se taire."],
  ["Tongue in cheek", "tongue in cheek", "Ironique, pince-sans-rire."],
  ["Lose touch", "^lose touch", "Perdre le contact."],
  ["Out of touch", "", "Déconnecté (de la réalité), plus au courant."],
  ["Keep one's head above water", "^keep one's head above water", "Garder la tête hors de l'eau, s'en sortir tout juste."],
  ["Keep one's chin up", "^keep one's chin up", "Garder le moral."],
  ["Lose one's mind", "^lose one's mind", "Perdre la tête, devenir fou."],
  ["Out of one's mind", "out of one's mind", "Fou, avoir perdu la tête."],
  ["Cross one's mind", "^cross one's mind", "Venir à l'esprit."],
  ["Speak one's mind", "^speak one's mind", "Dire franchement ce qu'on pense."],
  ["Change one's mind", "^change one's mind", "Changer d'avis."],
  ["Peace of mind", "", "La tranquillité d'esprit."],
  ["Mind one's own business", "^mind one's own business", "Se mêler de ses affaires."],
  ["Never mind", "", "Peu importe, laisse tomber."],
  ["Slip one's mind", "^slip one's mind", "Sortir de la tête, oublier."],
  ["Get carried away", "^get carried away", "Se laisser emporter."],
  ["The cold shoulder", "", "Battre froid, ignorer quelqu'un."],
  ["A shoulder to cry on", "", "Une épaule sur laquelle pleurer."],
  ["Rub salt in the wound", "^rub salt (in|into) … (wound|wounds)", "Retourner le couteau dans la plaie."],
  ["Elbow grease", "", "De l'huile de coude, des efforts."],
  ["A pretty penny", "", "Une jolie somme, une petite fortune."],
  ["The penny dropped", "the penny (dropped|drops)", "Il (j') a enfin compris, ça a fait tilt."],
  ["Make a killing", "^make a killing", "Faire un gros bénéfice, se remplir les poches."],
  ["Break the bank", "^break the bank", "Se ruiner, coûter une fortune."],
  ["Tighten one's belt", "^tighten one's belt", "Se serrer la ceinture."],
  ["Money doesn't grow on trees", "money does not grow on trees", "L'argent ne pousse pas sur les arbres."],
  ["In the red", "", "Dans le rouge, à découvert."],
  ["Red tape", "", "La paperasserie, la bureaucratie."],
  ["Caught red-handed", "red-handed", "Pris la main dans le sac."],
  ["Paint the town red", "^paint the town red", "Faire la fête, faire la tournée des grands-ducs."],
  ["Once in a lifetime", "", "Unique dans une vie."],
  ["Out of the woods", "", "Tiré d'affaire."],
  ["Can't see the wood for the trees", "the (wood|forest|woods) for the trees", "L'arbre qui cache la forêt : se perdre dans les détails."],
  ["Touch wood", "(touch|knock on) wood", "Je touche du bois."],
  ["A drop in the ocean", "a drop in the (ocean|bucket)", "Une goutte d'eau dans la mer."],
  ["Water under the bridge", "", "C'est du passé, c'est oublié."],
  ["Like water off a duck's back", "off a duck 's back", "Ça glisse comme sur les plumes d'un canard."],
  ["Make waves", "^make waves", "Faire des vagues."],
  ["Smooth sailing", "(smooth|plain) sailing", "Sans encombre, comme sur des roulettes."],
  ["Take the plunge", "^take the plunge", "Se jeter à l'eau, se lancer."],
  ["Test the waters", "^test the (water|waters)", "Tâter le terrain."],
  ["Sink or swim", "", "Se débrouiller seul : ça passe ou ça casse."],
  ["Go overboard", "^go overboard", "En faire trop."],
  ["In deep water", "", "Dans de beaux draps."],
  ["Keep one's cool", "^keep one's cool", "Garder son sang-froid."],
  ["Lose one's cool", "^lose one's cool", "Perdre son sang-froid."],
  ["Raise the bar", "^raise the bar", "Placer la barre plus haut."],
  ["Up to scratch", "up to (scratch|par)", "À la hauteur, au niveau."],
  ["Below par", "", "En dessous de la normale, pas en forme."],
  ["Fall short", "^fall short", "Ne pas être à la hauteur, être insuffisant."],
  ["Fall apart", "^fall apart", "S'effondrer, partir en morceaux."],
  ["Fall into place", "^fall into place", "Se mettre en place, s'éclaircir."],
  ["Fall in love", "^fall in love", "Tomber amoureux."],
  ["Take a step back", "^take a step back", "Prendre du recul."],
  ["Take it or leave it", "", "C'est à prendre ou à laisser."],
  ["Take one's time", "^take one's time", "Prendre son temps."],
  ["Take a chance", "^take a (chance|risk)", "Tenter sa chance, prendre un risque."],
  ["Take part in", "^take part in", "Participer à."],
  ["Take place", "^take place", "Avoir lieu."],
  ["Take care of", "^take care of", "S'occuper de, prendre soin de."],
  ["Keep up with", "^keep up with", "Suivre le rythme de ; se tenir au courant de."],
  ["Catch up", "^catch up (with|on)", "Rattraper ; se mettre à jour."],
  ["Come across", "^come across", "Tomber sur ; donner l'impression (d'être)."],
  ["Get along with", "^get along with", "S'entendre avec."],
  ["Get over it", "^get over (it|him|her|that|this|them)", "S'en remettre, passer à autre chose."],
  ["Look up to", "^look up to", "Admirer, prendre pour modèle."],
  ["Look down on", "^look down on", "Mépriser, regarder de haut."],
  ["Put off", "^put off", "Remettre à plus tard ; rebuter."],
  ["Bring up", "^bring up", "Élever (un enfant) ; aborder (un sujet)."],
  ["Point out", "^point out", "Faire remarquer, souligner."],
  ["Work out", "^work out", "Résoudre, trouver ; s'entraîner ; bien finir."],
  ["Make up for", "^make up for", "Compenser, rattraper."],
  ["Run into", "^run into", "Tomber sur (quelqu'un) ; rencontrer (un problème)."],
  ["Stand out", "^stand out", "Se démarquer, ressortir."],
  ["Hold on", "^hold on", "Attendre ; tenir bon."],
  ["Set out to", "^set out to", "Entreprendre de, se donner pour but de."],
  ["Live up to", "^live up to", "Être à la hauteur de."],
  ["End up", "^end up", "Finir par, se retrouver (à)."],
  ["Go through", "^go through", "Traverser (une épreuve) ; passer en revue."],
  ["Be about to", "^be about to", "Être sur le point de."],
  ["Used to", "", "Avoir l'habitude de (au passé), autrefois.", "Be used to + -ing : être habitué à."],
  ["Had better", "(had|'d) better", "Ferait mieux de."],
  ["Would rather", "(would|'d) rather", "Préférer, aimer mieux."],
  ["As if", "as (if|though)", "Comme si."],
  ["Apart from", "", "À part, en dehors de."],
  ["In spite of", "", "Malgré."],
  ["Even though", "even (though|if)", "Même si, bien que."],
  ["As well as", "", "Ainsi que, en plus de."],
  ["As long as", "", "Tant que, pourvu que."],
  ["As soon as", "", "Dès que."],
  ["In order to", "", "Afin de."],
  ["Rather than", "", "Plutôt que."],
  ["No matter", "no matter (what|how|where|when|who|if|whether)", "Peu importe, quoi que."],
  ["After all", "", "Après tout."],
  ["At least", "", "Au moins."],
  ["At last", "", "Enfin."],
  ["On the whole", "", "Dans l'ensemble."],
  ["So to speak", "", "Pour ainsi dire."],
  ["That being said", "", "Cela dit."],
  ["Needless to say", "", "Inutile de dire que."],
  ["Little by little", "", "Petit à petit."],
  ["Step by step", "", "Pas à pas."],
  ["Day in, day out", "day in day out", "Jour après jour, sans relâche."],
  ["Over and over", "over and over again?", "Encore et encore."],
  ["For the time being", "", "Pour le moment."],
  ["In the first place", "", "D'abord ; dès le départ."],
  ["On the spot", "", "Sur-le-champ ; sur place."],
  ["Off the record", "", "Officieusement, entre nous."],
  ["Behind the scenes", "", "En coulisses."],
  ["Hands down", "", "Haut la main, sans conteste."],
  ["Get one's hands dirty", "^get one's hands dirty", "Mettre la main à la pâte."],
  ["Have one's hands full", "one's hands full", "Être débordé."],
  ["Give someone a hand", "^give sb a hand", "Donner un coup de main (ou applaudir)."],
  ["Hand in hand", "", "Main dans la main ; aller de pair."],
  ["Second nature", "", "Une seconde nature."],
  ["Second to none", "", "Sans égal."],
  ["Old habits die hard", "", "Chassez le naturel, il revient au galop."],
  ["Easy come, easy go", "easy come easy go", "Ce qui vient facilement repart facilement."],
  ["Like father, like son", "like father like son", "Tel père, tel fils."],
  ["Birds of a feather", "", "Qui se ressemble s'assemble."],
  ["Two heads are better than one", "", "Deux avis valent mieux qu'un."],
  ["Great minds think alike", "", "Les grands esprits se rencontrent."],
  ["Rome wasn't built in a day", "rome was not built in a day", "Paris ne s'est pas fait en un jour."],
  ["Put the cart before the horse", "the cart before the horse", "Mettre la charrue avant les bœufs."],
  ["Look before you leap", "", "Il faut réfléchir avant d'agir."],
  ["Every dog has its day", "", "À chacun son heure de gloire."],
  ["A bird in the hand", "", "Un tiens vaut mieux que deux tu l'auras."],
  ["Have one's cake and eat it", "^have one's cake and eat it", "Avoir le beurre et l'argent du beurre."],
  ["The apple doesn't fall far from the tree", "the apple does not fall far", "Les chiens ne font pas des chats."],
  ["Bite the dust", "^bite the dust", "Mordre la poussière ; échouer, disparaître."],
  ["A skeleton in the closet", "(skeleton|skeletons) in … (closet|cupboard)", "Un secret honteux, un cadavre dans le placard."],
  ["Let one's hair down", "^let one's hair down", "Se lâcher, se détendre."],
  ["Keep someone posted", "^keep sb posted", "Tenir quelqu'un au courant."],
  ["Get to the point", "^get to the point", "En venir au fait."],
  ["Beside the point", "", "Hors sujet, sans rapport."],
  ["The point of no return", "", "Le point de non-retour."],
  ["Up to you", "up to (you|me|him|her|them|us)", "C'est à toi (lui…) de décider."],
  ["Hit it off", "^hit it off", "Bien s'entendre tout de suite, accrocher."],
  ["Hit home", "^hit home", "Faire mouche, toucher juste."],
  ["Strike a chord", "^strike a chord", "Toucher une corde sensible, rappeler quelque chose."],
  ["Strike a balance", "^strike a balance", "Trouver le juste équilibre."],
  ["Food for thought", "", "Matière à réflexion."],
  ["Wishful thinking", "", "Prendre ses désirs pour des réalités."],
  ["A long shot", "", "Un pari risqué, peu probable."],
  ["Make a point of", "^make a point of", "Mettre un point d'honneur à."],
  ["Make the best of", "^make the best of", "S'accommoder de, faire au mieux avec."],
  ["Make do", "^make do", "Se débrouiller, faire avec."],
  ["Make or break", "", "Décisif : ça passe ou ça casse."],
  ["Do the trick", "^do the trick", "Faire l'affaire."],
  ["Go for it", "^go for it", "Vas-y, fonce !"],
  ["Have a go", "^have a go", "Essayer, tenter le coup."],
  ["Have a blast", "^have a blast", "S'éclater, s'amuser comme un fou."],
  ["Have a point", "^have a point", "Ne pas avoir tort."],
  ["Have no idea", "^have no idea", "N'avoir aucune idée."],
  ["Have a word with", "^have a word with", "Toucher deux mots à."],
  ["In other words", "", "Autrement dit."],
  ["Word of mouth", "", "Le bouche-à-oreille."],
  ["Take someone's word for it", "^take one's word for it", "Croire quelqu'un sur parole."],
  ["Mark my words", "", "Croyez-moi, retenez bien ce que je dis."],
  ["Eat one's words", "^eat one's words", "Ravaler ses paroles."],
  ["Lost for words", "(lost|at a loss) for words", "Sans voix, à court de mots."],
  ["In the spotlight", "", "Sous les projecteurs."],
  ["Steal someone's thunder", "^steal one's thunder", "Couper l'herbe sous le pied, voler la vedette."],
  ["A wake-up call", "", "Un signal d'alarme, une prise de conscience."],
  ["Smell the coffee", "smell the coffee", "Ouvrir les yeux sur la réalité."],
  ["Bring home the bacon", "^bring home the bacon", "Faire bouillir la marmite."],
  ["Butter someone up", "^butter sb up", "Passer de la pommade, flatter."],
  ["Sour grapes", "", "Les raisins sont trop verts : du dépit."],
  ["Bread and butter", "", "Le gagne-pain ; l'essentiel."],
  ["Spice things up", "^spice … up", "Pimenter, mettre du piquant."],
  ["Walk on eggshells", "^walk on eggshells", "Marcher sur des œufs."],
  ["A sweet tooth", "", "Être gourmand (de sucreries)."],
  ["Full of beans", "", "Plein d'énergie, en pleine forme."],
  ["Cool as a cucumber", "", "Imperturbable, d'un calme olympien."],
  ["Packed like sardines", "like sardines", "Serrés comme des sardines."],
  ["Hit the books", "^hit the books", "Se mettre à étudier, bûcher."],
  ["The hard way", "", "À ses dépens, à la dure."],
  ["Inside out", "", "Par cœur, sur le bout des doigts ; à l'envers."],
  ["Ups and downs", "", "Des hauts et des bas."],
  ["Odds and ends", "", "Des bricoles, des bouts de chose."],
  ["Pros and cons", "", "Le pour et le contre."],
  ["Safe and sound", "", "Sain et sauf."],
  ["Sick and tired", "", "En avoir ras-le-bol."],
  ["Short and sweet", "", "Bref et efficace."],
  ["Now or never", "", "C'est maintenant ou jamais."],
  ["Better off", "", "Mieux, dans une meilleure situation."],
  ["Find oneself", "^find oneself", "Se trouver (soi-même) ; se retrouver (dans une situation)."],
  ["True to oneself", "true to oneself", "Fidèle à soi-même."],
  ["Come into one's own", "^come into one's own", "Trouver sa voie, s'épanouir."],
  ["In one's element", "in one's element", "Dans son élément."],
  ["Comfort zone", "", "La zone de confort."],
  ["Get a grip", "^get a grip", "Se ressaisir."],
  ["Bounce back", "^bounce back", "Rebondir, se remettre."],
  ["Turn over a new leaf", "^turn over a new leaf", "Tourner la page, repartir sur de bonnes bases."],
  ["Turn the page", "^turn the page", "Tourner la page."],
  ["Turn the tables", "^turn the tables", "Renverser la situation."],
  ["A new lease of life", "a new lease (of|on) life", "Un nouveau souffle, une seconde jeunesse."],
  ["Get a kick out of", "^get a kick out of", "Prendre plaisir à, adorer."],
  ["Blow one's mind", "^blow one's mind", "Époustoufler, sidérer."],
  ["Mind-blowing", "", "Époustouflant."],
  ["Jaw-dropping", "", "Stupéfiant, à couper le souffle."],
  ["Eye-opening", "(eye-opening|eye-opener)", "Révélateur, qui ouvre les yeux."],
  ["Catch someone's eye", "^catch one's eye", "Attirer l'attention (de quelqu'un)."],
  ["An eye for an eye", "", "Œil pour œil."],
  ["Turn heads", "^turn heads", "Faire tourner les têtes."],
  ["Head in the sand", "", "Faire l'autruche."],
  ["Head and shoulders above", "", "Nettement supérieur à."],
  ["Off the hook", "", "Tiré d'affaire, libéré d'une obligation."],
  ["Hook, line and sinker", "hook line and sinker", "Tout gober, mordre à l'hameçon."],
  ["Jump to conclusions", "^jump to conclusions", "Tirer des conclusions hâtives."],
  ["The green light", "", "Le feu vert."],
  ["A red flag", "a red flag", "Un signal d'alarme, un mauvais signe."],
  ["Out of the box", "", "Prêt à l'emploi ; original, hors des sentiers battus."],
  ["Neck of the woods", "", "Coin, région (par chez nous)."],
  ["Up for grabs", "", "À prendre, disponible."],
  ["Up and running", "", "Opérationnel, en marche."],
  ["The ins and outs", "", "Les tenants et les aboutissants."],
  ["Cut it out", "", "Arrête ça !"],
  ["Not to mention", "", "Sans parler de."],
  ["Let alone", "", "Et encore moins."],
  ["To say the least", "", "C'est le moins qu'on puisse dire."],
  ["For the sake of", "", "Pour, dans l'intérêt de."],
  ["For sure", "", "C'est sûr, à coup sûr."],
  ["Sure enough", "", "Effectivement, comme prévu."],
  ["Out of nowhere", "", "De nulle part, soudainement."],
  ["The other way around", "the other way (around|round)", "L'inverse, dans l'autre sens."],
  ["On one's own", "on one's own", "Seul, par soi-même."],
  ["Get the better of", "^get the better of", "Prendre le dessus sur."],
  ["Get on with", "^get on with", "Poursuivre ; s'entendre avec."],
  ["In common", "", "En commun."],
  ["Common ground", "", "Un terrain d'entente."],
  ["Common sense", "", "Le bon sens."]
];
