/* Expressions idiomatiques reconnues dans les textes.
   Chaque ligne : [forme affichée, motif de recherche ('' = la forme affichée), sens en français, note facultative]
   Motif : ^verbe = toutes les formes du verbe (break, broke, broken…) ;
           (a|b) = au choix ; one's = my/your/his/her/its/our/their ou « X's » ;
           oneself = myself/yourself… ; sb, sth = un à trois mots quelconques ;
           mot? = mot facultatif. */
const IDIOMS = [
  ["There is such a thing as too much…", "there (is|was|'s) such a thing as too (much|many)", "On peut avoir trop de… ; l'excès nuit en tout.", "Formule très courante : « trop de … tue le … »."],
  ["There is no such thing as…", "there (is|was|'s) no such thing as", "… n'existe pas ; il n'y a pas de…", "Ex. : There's no such thing as a free lunch — rien n'est gratuit."],
  ["No such thing as a free lunch", "no such thing as a free lunch", "Rien n'est gratuit ; tout se paie."],
  ["Break the ice", "^break the ice", "Briser la glace."],
  ["Call it a day", "^call it a day", "S'arrêter là (pour aujourd'hui)."],
  ["Call it quits", "^call it quits", "En rester là, arrêter."],
  ["A piece of cake", "", "C'est du gâteau, c'est très facile."],
  ["Hit the nail on the head", "^hit the nail on the head", "Mettre le doigt dessus, viser juste."],
  ["Spill the beans", "^spill the beans", "Vendre la mèche."],
  ["Let the cat out of the bag", "^let the cat out of the bag", "Vendre la mèche."],
  ["Under the weather", "", "Patraque, pas en forme."],
  ["Once in a blue moon", "", "Tous les trente-six du mois, très rarement."],
  ["Cost an arm and a leg", "^cost an arm and a leg", "Coûter les yeux de la tête."],
  ["Bite the bullet", "^bite the bullet", "Serrer les dents et s'y résoudre."],
  ["Beat around the bush", "^beat (around|about) the bush", "Tourner autour du pot."],
  ["The last straw", "the (last|final) straw", "La goutte d'eau qui fait déborder le vase."],
  ["Miss the boat", "^miss the boat", "Rater le coche."],
  ["Pull someone's leg", "^pull one's leg", "Faire marcher quelqu'un, le taquiner."],
  ["See eye to eye", "^see eye to eye", "Être d'accord, voir les choses de la même façon."],
  ["Cut corners", "^cut corners", "Bâcler, rogner sur la qualité."],
  ["Get out of hand", "^get out of hand", "Échapper à tout contrôle, dégénérer."],
  ["Hang in there", "^hang in there", "Tiens bon !"],
  ["Not rocket science", "not rocket science", "Ce n'est pas sorcier."],
  ["Keep an eye on", "^keep an eye on", "Surveiller, garder un œil sur."],
  ["Go the extra mile", "^go the extra mile", "Faire un effort supplémentaire."],
  ["Make ends meet", "^make ends meet", "Joindre les deux bouts."],
  ["On the same page", "", "Sur la même longueur d'onde, d'accord sur l'essentiel."],
  ["Play it by ear", "^play it by ear", "Improviser, aviser au fur et à mesure."],
  ["Ring a bell", "^ring a bell", "Dire quelque chose (rappeler un souvenir)."],
  ["Take it easy", "^take it easy", "Se détendre ; y aller doucement."],
  ["Better late than never", "", "Mieux vaut tard que jamais."],
  ["The ball is in your court", "the ball (is|'s) in one's court", "La balle est dans ton camp : à toi d'agir."],
  ["Add insult to injury", "^add insult to injury", "Retourner le couteau dans la plaie ; pour ne rien arranger."],
  ["Get the hang of", "^get the hang of", "Prendre le coup de main pour."],
  ["Jump on the bandwagon", "^jump on the bandwagon", "Prendre le train en marche, suivre la mode."],
  ["Kill two birds with one stone", "^kill two birds with one stone", "Faire d'une pierre deux coups."],
  ["The elephant in the room", "", "Le sujet que tout le monde évite."],
  ["A blessing in disguise", "", "Un mal pour un bien."],
  ["Every cloud has a silver lining", "", "À quelque chose malheur est bon."],
  ["Speak of the devil", "(speak|speaking|talk|talking) of the devil", "Quand on parle du loup…"],
  ["Hit the sack", "^hit the (sack|hay)", "Aller se coucher."],
  ["Sit on the fence", "^sit on the fence", "Ne pas prendre parti."],
  ["Steal the show", "^steal the show", "Voler la vedette."],
  ["Take a rain check", "^take a rain check", "Remettre (une invitation) à plus tard."],
  ["Throw in the towel", "^throw in the towel", "Jeter l'éponge."],
  ["Cry over spilt milk", "^cry over (spilt|spilled) milk", "Se lamenter sur ce qui est fait et ne peut être changé."],
  ["Burn the midnight oil", "^burn the midnight oil", "Travailler tard dans la nuit."],
  ["Burn one's bridges", "^burn one's? bridges", "Couper les ponts, se fermer toute possibilité de retour."],
  ["Cross that bridge when we come to it", "^cross that bridge when sb ^come to it", "Chaque chose en son temps ; on verra le moment venu."],
  ["Face the music", "^face the music", "Assumer les conséquences."],
  ["Get cold feet", "^get cold feet", "Avoir la frousse, se dégonfler au dernier moment."],
  ["Back to the drawing board", "back to the drawing board", "Retour à la case départ (il faut tout repenser)."],
  ["Back to square one", "", "Retour à la case départ."],
  ["In the nick of time", "", "Juste à temps."],
  ["It takes two to tango", "^take two to tango", "Il faut être deux ; les torts sont partagés."],
  ["Leave no stone unturned", "^leave no stone unturned", "Remuer ciel et terre."],
  ["Let sleeping dogs lie", "", "Ne pas réveiller le chat qui dort."],
  ["No pain, no gain", "no pain no gain", "On n'a rien sans rien."],
  ["On thin ice", "", "Sur un terrain glissant."],
  ["Pull oneself together", "^pull oneself together", "Se ressaisir."],
  ["Rain cats and dogs", "^rain cats and dogs", "Pleuvoir des cordes."],
  ["Light at the end of the tunnel", "", "Le bout du tunnel."],
  ["So far, so good", "so far so good", "Jusqu'ici, tout va bien."],
  ["The best of both worlds", "", "Le meilleur des deux mondes."],
  ["With a grain of salt", "with a (grain|pinch) of salt", "Avec des pincettes, avec réserve."],
  ["Time flies", "time (flies|flew)", "Le temps passe vite."],
  ["Long story short", "", "Bref, pour faire court."],
  ["Twist someone's arm", "^twist one's arm", "Forcer la main à quelqu'un."],
  ["Under the radar", "", "Discrètement, sans attirer l'attention."],
  ["Wrap one's head around", "^wrap one's head around", "Arriver à comprendre (quelque chose de complexe)."],
  ["Judge a book by its cover", "^judge a book by its cover", "Juger sur les apparences.", "Don't judge a book by its cover : l'habit ne fait pas le moine."],
  ["A dime a dozen", "", "Monnaie courante, il y en a à la pelle."],
  ["Actions speak louder than words", "", "Les actes comptent plus que les paroles."],
  ["Bark up the wrong tree", "^bark up the wrong tree", "Faire fausse route, se tromper de cible."],
  ["In hot water", "", "Dans le pétrin."],
  ["Bend over backwards", "^bend over backwards", "Se mettre en quatre."],
  ["Between a rock and a hard place", "", "Entre le marteau et l'enclume."],
  ["By the skin of one's teeth", "by the skin of one's teeth", "De justesse."],
  ["Call the shots", "^call the shots", "Mener la barque, décider."],
  ["Come rain or shine", "", "Quoi qu'il arrive, qu'il pleuve ou qu'il vente."],
  ["Cut to the chase", "^cut to the chase", "Aller droit au but."],
  ["Down to earth", "down to earth", "Les pieds sur terre, simple."],
  ["Drop the ball", "^drop the ball", "Commettre une erreur, laisser tomber une responsabilité."],
  ["Easier said than done", "", "Plus facile à dire qu'à faire."],
  ["A fish out of water", "", "Comme un poisson hors de l'eau, pas à sa place."],
  ["A taste of one's own medicine", "a taste of one's own medicine", "La monnaie de sa pièce."],
  ["Get something off one's chest", "off one's chest", "Vider son sac, dire ce qu'on a sur le cœur."],
  ["The benefit of the doubt", "", "Le bénéfice du doute."],
  ["Go with the flow", "^go with the flow", "Se laisser porter, suivre le mouvement."],
  ["A lot on one's plate", "(a lot|lots|enough|too much) on one's plate", "Avoir du pain sur la planche."],
  ["Head over heels", "", "Éperdument (amoureux)."],
  ["Hit the road", "^hit the road", "Se mettre en route, partir."],
  ["Hold your horses", "^hold one's horses", "Du calme, pas si vite !"],
  ["In a nutshell", "", "En un mot, en résumé."],
  ["Keep one's fingers crossed", "fingers crossed", "Croiser les doigts."],
  ["Know the ropes", "^(know|learn|show) sb? the ropes", "Connaître (apprendre, montrer) les ficelles."],
  ["Let off steam", "^(let|blow) off steam", "Se défouler, décompresser."],
  ["Lose one's temper", "^lose one's temper", "Se mettre en colère, perdre son calme."],
  ["Make a mountain out of a molehill", "^make a mountain out of a molehill", "En faire tout un plat, une montagne."],
  ["Miss the point", "^miss the point", "Passer à côté de l'essentiel."],
  ["Not my cup of tea", "not one's cup of tea", "Ce n'est pas mon truc."],
  ["Off the top of my head", "off the top of one's head", "De mémoire, comme ça, sans vérifier."],
  ["On cloud nine", "", "Aux anges, au septième ciel."],
  ["Once and for all", "", "Une fois pour toutes."],
  ["Out of the blue", "", "Sans prévenir, tout à coup."],
  ["Over the moon", "", "Fou de joie, ravi."],
  ["Pass the buck", "^pass the buck", "Refiler la responsabilité à quelqu'un d'autre."],
  ["Put all one's eggs in one basket", "all one's eggs in one basket", "Mettre tous ses œufs dans le même panier."],
  ["Read between the lines", "^read between the lines", "Lire entre les lignes."],
  ["Run out of steam", "^run out of steam", "S'essouffler, être à bout."],
  ["Save face", "^save face", "Sauver la face."],
  ["Set in stone", "", "Gravé dans le marbre, définitif."],
  ["Sleep on it", "^sleep on it", "Laisser reposer la décision : la nuit porte conseil."],
  ["Take the bull by the horns", "^take the bull by the horns", "Prendre le taureau par les cornes."],
  ["Tie the knot", "^tie the knot", "Se marier."],
  ["The tip of the iceberg", "", "La partie émergée de l'iceberg."],
  ["The whole nine yards", "", "Le grand jeu, jusqu'au bout."],
  ["To be honest", "", "Pour être honnête, à vrai dire."],
  ["To tell the truth", "", "À vrai dire."],
  ["Turn a blind eye", "^turn a blind eye", "Fermer les yeux (sur quelque chose)."],
  ["Up in the air", "", "Incertain, en suspens."],
  ["Weather the storm", "^weather the storm", "Surmonter la tempête, tenir le coup."],
  ["When pigs fly", "when pigs (fly|can fly)", "Quand les poules auront des dents."],
  ["A penny for your thoughts", "", "À quoi penses-tu ?"],
  ["Cold turkey", "", "Arrêter net, d'un coup (une habitude, une drogue)."],
  ["Get the ball rolling", "^(get|set|start) the ball rolling", "Lancer les choses, amorcer."],
  ["Jump the gun", "^jump the gun", "Agir trop tôt, griller les étapes."],
  ["At arm's length", "at arm 's length", "À distance (garder quelqu'un à distance)."],
  ["By and large", "", "Dans l'ensemble."],
  ["All of a sudden", "", "Tout à coup."],
  ["As a matter of fact", "", "En fait, à vrai dire."],
  ["At the end of the day", "", "En fin de compte."],
  ["At the drop of a hat", "", "Sur-le-champ, sans hésiter."],
  ["Beat a dead horse", "^(beat|flog) a dead horse", "S'acharner pour rien, insister inutilement."],
  ["Bite off more than one can chew", "^bite off more than sb can chew", "Avoir les yeux plus gros que le ventre."],
  ["Break a leg", "^break a leg", "Bonne chance ! (au théâtre : « merde ! »)"],
  ["Come to terms with", "^come to terms with", "Accepter, se faire à."],
  ["Cut someone some slack", "^cut sb some slack", "Être indulgent avec quelqu'un."],
  ["Get one's act together", "^get one's act together", "Se reprendre en main, se secouer."],
  ["Give it a shot", "^give it a (shot|try|go|whirl)", "Essayer, tenter le coup."],
  ["It goes without saying", "^go without saying", "Ça va sans dire."],
  ["Have second thoughts", "^have second thoughts", "Avoir des doutes, hésiter à nouveau."],
  ["In the long run", "", "À long terme."],
  ["In the same boat", "", "Dans le même bateau, dans la même galère."],
  ["It's about time", "it (is|'s|was) about time", "Il était temps."],
  ["Keep in touch", "^(keep|stay|get) in touch", "Rester (se mettre) en contact."],
  ["Make up one's mind", "^make up one's mind", "Se décider."],
  ["No wonder", "", "Pas étonnant (que)."],
  ["Take for granted", "^take sb? for granted", "Tenir pour acquis."],
  ["The bottom line", "", "L'essentiel, le fin mot de l'histoire."],
  ["Think outside the box", "^think outside the box", "Sortir des sentiers battus."],
  ["Touch base", "^touch base", "Reprendre contact, faire un point rapide."],
  ["A far cry from", "", "Très loin de, rien à voir avec."],
  ["Make sense", "^make sense", "Avoir du sens, être logique."],
  ["On the other hand", "", "D'un autre côté, en revanche."],
  ["By the way", "", "Au fait, à propos."],
  ["Bear in mind", "^(bear|keep) in mind", "Garder à l'esprit."],
  ["Pull strings", "^pull (some|a few)? strings", "Faire jouer ses relations, pistonner."],
  ["Rock the boat", "^rock the boat", "Faire des vagues, semer le trouble."],
  ["Stab someone in the back", "^stab sb in the back", "Trahir, poignarder dans le dos."],
  ["Shoot oneself in the foot", "^shoot oneself in the foot", "Se tirer une balle dans le pied."],
  ["The devil is in the details", "the devil (is|'s) in the detail", "Le diable se cache dans les détails."],
  ["Down the rabbit hole", "", "Se perdre dans un sujet sans fin."],
  ["A chip on one's shoulder", "a chip on one's shoulder", "Être aigri, avoir une rancune tenace."],
  ["Devil's advocate", "devil 's advocate", "L'avocat du diable."],
  ["Pull one's weight", "^pull one's weight", "Faire sa part (du travail)."],
  ["A storm in a teacup", "a storm in a teacup", "Une tempête dans un verre d'eau."],
  ["Put one's foot in it", "^put one's foot in (it|one's mouth)", "Mettre les pieds dans le plat, faire une gaffe."],
  ["Get on someone's nerves", "^get on one's nerves", "Taper sur les nerfs."],
  ["Drive someone up the wall", "^drive sb up the wall", "Rendre quelqu'un fou (d'exaspération)."],
  ["Butterflies in one's stomach", "butterflies in one's stomach", "Avoir le trac, l'estomac noué."],
  ["See red", "^see red", "Voir rouge, se mettre en colère."],
  ["A bitter pill to swallow", "", "Une pilule difficile à avaler."],
  ["Hit the ground running", "^hit the ground running", "Démarrer sur les chapeaux de roue."],
  ["Too good to be true", "", "Trop beau pour être vrai."],
  ["Take a toll", "^take (a|its|their|his|her|an) (heavy)? toll", "Avoir des effets néfastes, laisser des traces."],
  ["Make no bones about", "^make no bones about", "Ne pas cacher, dire franchement."],
  ["Go to great lengths", "^go to (great|any|extraordinary) lengths", "Se donner beaucoup de mal, ne reculer devant rien."],
  ["More often than not", "", "Le plus souvent."],
  ["Stand one's ground", "^stand one's ground", "Tenir bon, ne pas céder."],
  ["Have the last laugh", "^have the last laugh", "Rira bien qui rira le dernier."],
  ["Get the picture", "^get the picture", "Piger, comprendre la situation."],
  ["It's a small world", "it (is|'s) a small world", "Le monde est petit."],
  ["Kick the bucket", "^kick the bucket", "Casser sa pipe (mourir)."],
  ["Bury the hatchet", "^bury the hatchet", "Enterrer la hache de guerre."],
  ["Go out on a limb", "^go out on a limb", "Prendre un risque, s'avancer."],
  ["Head in the clouds", "head in the clouds", "Avoir la tête dans les nuages."],
  ["Lend a hand", "^lend sb? a hand", "Donner un coup de main."],
  ["Put up with", "^put up with", "Supporter, tolérer."],
  ["Look forward to", "^look forward to", "Avoir hâte de, attendre avec impatience."],
  ["Fed up with", "fed up", "En avoir marre (de)."],
  ["Have a crush on", "^have a crush on", "Avoir le béguin pour."],
  ["On purpose", "", "Exprès, délibérément."],
  ["By heart", "", "Par cœur."],
  ["At stake", "", "En jeu."],
  ["For what it's worth", "for what (it's|it is) worth", "Pour ce que ça vaut."],
  ["The more the merrier", "", "Plus on est de fous, plus on rit."],
  ["Better safe than sorry", "", "Prudence est mère de sûreté."],
  ["Curiosity killed the cat", "", "La curiosité est un vilain défaut."],
  ["When in Rome", "", "À Rome, fais comme les Romains."],
  ["The early bird catches the worm", "the early bird", "L'avenir appartient à ceux qui se lèvent tôt."],
  ["Don't count your chickens", "^count one's chickens", "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué."],
  ["Practice makes perfect", "", "C'est en forgeant qu'on devient forgeron."],
  ["Out of sight, out of mind", "out of sight out of mind", "Loin des yeux, loin du cœur."],
  ["The grass is always greener", "the grass is always greener", "L'herbe est toujours plus verte ailleurs."],
  ["Under the same roof", "", "Sous le même toit."],
  ["A matter of time", "", "Une question de temps."],
  ["In the meantime", "", "En attendant, entre-temps."],
  ["Sooner or later", "", "Tôt ou tard."],
  ["Every now and then", "every (now and then|now and again|so often)", "De temps en temps."],
  ["As far as I know", "as far as (i|we) know", "Pour autant que je sache."],
  ["Last but not least", "", "Enfin et surtout ; le dernier mais pas le moindre."],
  ["Out of the question", "", "Hors de question."],
  ["Make the most of", "^make the most of", "Profiter au maximum de, tirer le meilleur parti de."],
  ["Get rid of", "^get rid of", "Se débarrasser de."],
  ["Take advantage of", "^take advantage of", "Profiter de ; abuser de."],
  ["Run out of", "^run out of", "Manquer de, être à court de."],
  ["Give up", "^give up", "Abandonner, renoncer."],
  ["Find out", "^find out", "Découvrir, apprendre."],
  ["Figure out", "^figure out", "Comprendre, trouver (la solution)."],
  ["Come up with", "^come up with", "Trouver, proposer (une idée)."],
  ["Carry on", "^carry on", "Continuer."]
];
